export const turfDetailsArray = [
  {
    turfName: 'Sunrise Arena',
    sportType: 'Football | Cricket',
    address: 'Vijaynagar, Mysuru',
    rating: '4.3',
    rate: '1200',
    distance: '1.8',
    slots: {
      '6am-7am': 'Available',
      '7am-8am': 'Booked',
      '8am-9am': 'Available',
      '9am-10am': 'Available',
      '10am-11am': 'Available',
      '11am-12pm': 'Available',
      '12pm-1pm': 'Available',
      '1pm-2pm': 'Available',
      '2pm-3pm': 'Available',
      '3pm-4pm': 'Available',
      '4pm-5pm': 'Booked',
      '5pm-6pm': 'Available',
      '6pm-7pm': 'Available',
      '7pm-8pm': 'Available',
      '8pm-9pm': 'Available',
      '9pm-10pm': 'Available',
    },
  },
  {
    turfName: 'MatchBox',
    sportType: 'Football | Cricket',
    address: 'Vijaynagar, Mysuru',
    rating: '3.2',
    rate: '1000',
    distance: '1.8',
    slots: {
      '6am-7am': 'Available',
      '7am-8am': 'Booked',
      '8am-9am': 'Available',
      '9am-10am': 'Available',
      '10am-11am': 'Available',
      '11am-12pm': 'Available',
      '12pm-1pm': 'Available',
      '1pm-2pm': 'Available',
      '2pm-3pm': 'Available',
      '3pm-4pm': 'Available',
      '4pm-5pm': 'Booked',
      '5pm-6pm': 'Available',
      '6pm-7pm': 'Available',
      '7pm-8pm': 'Available',
      '8pm-9pm': 'Available',
      '9pm-10pm': 'Available',
    },
  },
  {
    turfName: 'Velocity Arena',
    sportType: 'Badminton',
    address: 'Pune, Mysuru',
    rating: 'New',
    rate: '400',
    distance: '1.8',
    slots: {
      '6am-7am': 'Available',
      '7am-8am': 'Booked',
      '8am-9am': 'Available',
      '9am-10am': 'Available',
      '10am-11am': 'Available',
      '11am-12pm': 'Available',
      '12pm-1pm': 'Available',
      '1pm-2pm': 'Available',
      '2pm-3pm': 'Available',
      '3pm-4pm': 'Available',
      '4pm-5pm': 'Booked',
      '5pm-6pm': 'Available',
      '6pm-7pm': 'Available',
      '7pm-8pm': 'Available',
      '8pm-9pm': 'Available',
      '9pm-10pm': 'Available',
    },
  },
  {
    turfName: 'Astro Park',
    sportType: 'Football | Cricket',
    address: 'Mumbai',
    rating: '3.8',
    rate: '1500',
    distance: '2.8',
    slots: {
      '6am-7am': 'Available',
      '7am-8am': 'Booked',
      '8am-9am': 'Available',
      '9am-10am': 'Available',
      '10am-11am': 'Available',
      '11am-12pm': 'Available',
      '12pm-1pm': 'Available',
      '1pm-2pm': 'Available',
      '2pm-3pm': 'Available',
      '3pm-4pm': 'Available',
      '4pm-5pm': 'Booked',
      '5pm-6pm': 'Available',
      '6pm-7pm': 'Available',
      '7pm-8pm': 'Available',
      '8pm-9pm': 'Available',
      '9pm-10pm': 'Available',
    },
  },
  {
    turfName: 'Sector 42 Stadium',
    sportType: 'Hockey',
    address: 'Chandigarh',
    rating: '1.8',
    rate: '2000',
    distance: '4.5',
    slots: {
      '6am-7am': 'Available',
      '7am-8am': 'Booked',
      '8am-9am': 'Available',
      '9am-10am': 'Available',
      '10am-11am': 'Available',
      '11am-12pm': 'Available',
      '12pm-1pm': 'Available',
      '1pm-2pm': 'Available',
      '2pm-3pm': 'Available',
      '3pm-4pm': 'Available',
      '4pm-5pm': 'Booked',
      '5pm-6pm': 'Available',
      '6pm-7pm': 'Available',
      '7pm-8pm': 'Available',
      '8pm-9pm': 'Available',
      '9pm-10pm': 'Available',
    },
  },
];

export const ownerSlots = {
  slots: {
    '6am-7am': 'Available',
    '7am-8am': 'Booked',
    '8am-9am': 'Available',
    '11am-12pm': 'Available',
    '12pm-1pm': 'Available',
    '1pm-2pm': 'Available',
    '2pm-3pm': 'Available',
    '3pm-4pm': 'Available',
    '6pm-7pm': 'Available',
    '7pm-8pm': 'Available',
    '8pm-9pm': 'Available',
    '9pm-10pm': 'Available',
  },
};
